// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Article documents */
interface ArticleDocumentData {
    /**
     * Publish Date field in *Article*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: article.publish_date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    publish_date: prismicT.DateField;
    /**
     * Featured Image field in *Article*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: article.featured_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    featured_image: prismicT.ImageField<never>;
    /**
     * Excerpt field in *Article*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: article.excerpt
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    excerpt: prismicT.RichTextField;
    /**
     * Title field in *Article*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: article.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Article*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: article.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ArticleDocumentDataSlicesSlice>;
}
/**
 * Slice for *Article → Slice Zone*
 *
 */
type ArticleDocumentDataSlicesSlice = ImageSlice | TextSlice | QuoteSlice;
/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ArticleDocumentData>, "article", Lang>;
/** Content for BlogPage documents */
interface BlogpageDocumentData {
    /**
     * Title field in *BlogPage*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blogpage.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Articles field in *BlogPage*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: blogpage.articles[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    articles: prismicT.GroupField<Simplify<BlogpageDocumentDataArticlesItem>>;
}
/**
 * Item in BlogPage → Articles
 *
 */
export interface BlogpageDocumentDataArticlesItem {
}
/**
 * BlogPage document from Prismic
 *
 * - **API ID**: `blogpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogpageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<BlogpageDocumentData>, "blogpage", Lang>;
/** Content for homePage documents */
interface HomepageDocumentData {
    /**
     * Heading field in *homePage*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.heading
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    heading: prismicT.RichTextField;
    /**
     * About Me Heading field in *homePage*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.about_me_heading
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    about_me_heading: prismicT.TitleField;
    /**
     * Profile Picture field in *homePage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.profile_picture
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    profile_picture: prismicT.ImageField<never>;
    /**
     * About Me Body field in *homePage*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.about_me_body
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    about_me_body: prismicT.RichTextField;
    /**
     * Portfolio Heading field in *homePage*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.portfolio_heading
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    portfolio_heading: prismicT.TitleField;
    /**
     * Portfolio field in *homePage*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.portfolio[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    portfolio: prismicT.GroupField<Simplify<HomepageDocumentDataPortfolioItem>>;
    /**
     * Testimonial Heading field in *homePage*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.testimonial_heading
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    testimonial_heading: prismicT.TitleField;
    /**
     * Testimonials field in *homePage*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.testimonials[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    testimonials: prismicT.GroupField<Simplify<HomepageDocumentDataTestimonialsItem>>;
    /**
     * Clients field in *homePage*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.clients[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    clients: prismicT.GroupField<Simplify<HomepageDocumentDataClientsItem>>;
    /**
     * Slice Zone field in *homePage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
}
/**
 * Item in homePage → Portfolio
 *
 */
export interface HomepageDocumentDataPortfolioItem {
    /**
     * Title field in *homePage → Portfolio*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.portfolio[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *homePage → Portfolio*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.portfolio[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * GitHub Link field in *homePage → Portfolio*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.portfolio[].githublink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    githublink: prismicT.LinkField;
    /**
     * Live Link field in *homePage → Portfolio*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.portfolio[].live_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    live_link: prismicT.LinkField;
    /**
     * Screenshot field in *homePage → Portfolio*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.portfolio[].screenshot
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    screenshot: prismicT.ImageField<never>;
}
/**
 * Item in homePage → Testimonials
 *
 */
export interface HomepageDocumentDataTestimonialsItem {
    /**
     * Quote field in *homePage → Testimonials*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.testimonials[].quote
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    quote: prismicT.RichTextField;
    /**
     * Name field in *homePage → Testimonials*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.testimonials[].name
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    name: prismicT.TitleField;
    /**
     * Affiliation field in *homePage → Testimonials*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.testimonials[].affiliation
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    affiliation: prismicT.RichTextField;
    /**
     * Profile Picture field in *homePage → Testimonials*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.testimonials[].profile_picture
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    profile_picture: prismicT.ImageField<never>;
}
/**
 * Item in homePage → Clients
 *
 */
export interface HomepageDocumentDataClientsItem {
    /**
     * Client Logo field in *homePage → Clients*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.clients[].client_logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    client_logo: prismicT.ImageField<never>;
}
/**
 * Slice for *homePage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = never;
/**
 * homePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
export type AllDocumentTypes = ArticleDocument | BlogpageDocument | HomepageDocument;
/**
 * Primary content in Excerpt → Primary
 *
 */
interface ExcerptSliceDefaultPrimary {
    /**
     * Excerpt field in *Excerpt → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: excerpt.primary.excerpt
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    excerpt: prismicT.RichTextField;
}
/**
 * Default variation for Excerpt Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Excerpt`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ExcerptSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ExcerptSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Excerpt*
 *
 */
type ExcerptSliceVariation = ExcerptSliceDefault;
/**
 * Excerpt Shared Slice
 *
 * - **API ID**: `excerpt`
 * - **Description**: `Excerpt`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ExcerptSlice = prismicT.SharedSlice<"excerpt", ExcerptSliceVariation>;
/**
 * Primary content in Image → Primary
 *
 */
interface ImageSliceDefaultPrimary {
    /**
     * Description field in *Image → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: image.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Image field in *Image → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: image.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Image`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ImageSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Image*
 *
 */
type ImageSliceVariation = ImageSliceDefault;
/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: `Image`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageSlice = prismicT.SharedSlice<"image", ImageSliceVariation>;
/**
 * Primary content in Portfolio → Primary
 *
 */
interface HomeIntroductionSliceDefaultPrimary {
    /**
     * Title field in *Portfolio → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: home_introduction.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
}
/**
 * Item in Portfolio → Items
 *
 */
export interface HomeIntroductionSliceDefaultItem {
    /**
     * Project Title field in *Portfolio → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_introduction.items[].project_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    project_title: prismicT.RichTextField;
    /**
     * Project Description field in *Portfolio → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_introduction.items[].project_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    project_description: prismicT.RichTextField;
    /**
     * Project Screenshot field in *Portfolio → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home_introduction.items[].project_screenshot
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    project_screenshot: prismicT.ImageField<never>;
    /**
     * GitHub Link field in *Portfolio → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: home_introduction.items[].github_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    github_link: prismicT.LinkField;
    /**
     * Live Link field in *Portfolio → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: home_introduction.items[].live_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    live_link: prismicT.LinkField;
}
/**
 * Default variation for Portfolio Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HomeIntroduction`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomeIntroductionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HomeIntroductionSliceDefaultPrimary>, Simplify<HomeIntroductionSliceDefaultItem>>;
/**
 * Slice variation for *Portfolio*
 *
 */
type HomeIntroductionSliceVariation = HomeIntroductionSliceDefault;
/**
 * Portfolio Shared Slice
 *
 * - **API ID**: `home_introduction`
 * - **Description**: `HomeIntroduction`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomeIntroductionSlice = prismicT.SharedSlice<"home_introduction", HomeIntroductionSliceVariation>;
/**
 * Primary content in Project → Primary
 *
 */
interface ProjectSliceDefaultPrimary {
    /**
     * Title field in *Project → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: project.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Project → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: project.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Screen Shot field in *Project → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project.primary.screen_shot
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    screen_shot: prismicT.ImageField<never>;
    /**
     * Git hub Link field in *Project → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: project.primary.git_hub_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    git_hub_link: prismicT.LinkField;
    /**
     * Live Link field in *Project → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: project.primary.live_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    live_link: prismicT.LinkField;
}
/**
 * Default variation for Project Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Project`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ProjectSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Project*
 *
 */
type ProjectSliceVariation = ProjectSliceDefault;
/**
 * Project Shared Slice
 *
 * - **API ID**: `project`
 * - **Description**: `Project`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectSlice = prismicT.SharedSlice<"project", ProjectSliceVariation>;
/**
 * Primary content in Quote → Primary
 *
 */
interface QuoteSliceDefaultPrimary {
    /**
     * Quote field in *Quote → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: quote.primary.quote
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    quote: prismicT.RichTextField;
}
/**
 * Default variation for Quote Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Quote`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type QuoteSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<QuoteSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Quote*
 *
 */
type QuoteSliceVariation = QuoteSliceDefault;
/**
 * Quote Shared Slice
 *
 * - **API ID**: `quote`
 * - **Description**: `Quote`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type QuoteSlice = prismicT.SharedSlice<"quote", QuoteSliceVariation>;
/**
 * Primary content in Text → Primary
 *
 */
interface TextSliceDefaultPrimary {
    /**
     * Text field in *Text → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: text.primary.text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
}
/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Text`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TextSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Text*
 *
 */
type TextSliceVariation = TextSliceDefault;
/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: `Text`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextSlice = prismicT.SharedSlice<"text", TextSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ArticleDocumentData, ArticleDocumentDataSlicesSlice, ArticleDocument, BlogpageDocumentData, BlogpageDocumentDataArticlesItem, BlogpageDocument, HomepageDocumentData, HomepageDocumentDataPortfolioItem, HomepageDocumentDataTestimonialsItem, HomepageDocumentDataClientsItem, HomepageDocumentDataSlicesSlice, HomepageDocument, AllDocumentTypes, ExcerptSliceDefaultPrimary, ExcerptSliceDefault, ExcerptSliceVariation, ExcerptSlice, ImageSliceDefaultPrimary, ImageSliceDefault, ImageSliceVariation, ImageSlice, HomeIntroductionSliceDefaultPrimary, HomeIntroductionSliceDefaultItem, HomeIntroductionSliceDefault, HomeIntroductionSliceVariation, HomeIntroductionSlice, ProjectSliceDefaultPrimary, ProjectSliceDefault, ProjectSliceVariation, ProjectSlice, QuoteSliceDefaultPrimary, QuoteSliceDefault, QuoteSliceVariation, QuoteSlice, TextSliceDefaultPrimary, TextSliceDefault, TextSliceVariation, TextSlice };
    }
}
