// Code generated by Slice Machine. DO NOT EDIT.

import CodeBlock from './CodeBlock';
import Image from './Image';
import Quote from './Quote';
import Text from './Text';

export {
	CodeBlock,
	Image,
	Quote,
	Text,
};

export const components = {
	code_block: CodeBlock,
	image: Image,
	quote: Quote,
	text: Text,
};
