// Code generated by Slice Machine. DO NOT EDIT.

import Excerpt from './Excerpt';
import Image from './Image';
import Portfolio from './Portfolio';
import Project from './Project';
import Quote from './Quote';
import Text from './Text';

export {
	Excerpt,
	Image,
	Portfolio,
	Project,
	Quote,
	Text,
};

export const components = {
	excerpt: Excerpt,
	image: Image,
	home_introduction: Portfolio,
	project: Project,
	quote: Quote,
	text: Text,
};
