import Head from "next/head";

import ErrorPageLayout from "../templates/errorPagelayout";
import ErrorSection from "../components/sections/ErrorSection";

const Custom404 = () => {
  return (
    <>
      <Head>
        <title>[STU] 500</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ErrorPageLayout>
        <ErrorSection code="500" message="Server Error" />
      </ErrorPageLayout>
    </>
  );
};

export default Custom404;
