import Head from "next/head";

import ErrorLayout from "../templates/errorLayout";
import ErrorSection from "../components/sections/ErrorSection";

const ArticlePage = () => {
  return (
    <>
      <Head>
        <title>[STU] - HELLO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ErrorLayout>
        <ErrorSection code="HELLO" message="Page Not Found" />
      </ErrorLayout>
    </>
  );
};

export default ArticlePage;
